# Generated by Django 5.1.4 on 2025-03-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogpost_options_remove_blogpost_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
