# Generated by Django 5.1.4 on 2025-02-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
